---
title: "homework3"
format: html
date: 5/30/25
website: https://github.com/ButterEggs/ENVS-193DS_homework-03.git
---
```{r}
library(tidyverse)
library(dplyr)
library(here)
library(gt)
library(janitor)
library(here)
```

### Problem 1a. Personal data
[I could calculate the mean number of steps I took on school days versus non-school days to compare how my physical activity differs depending on whether I have class. This would be informative because on school days I often walk between classes, while on non-school days I tend to be working at my job which requires constant movement for a few hours, so I expect to have more steps on those days.]


```{r}
steps_data <- read.csv(here("data", "steps_data.csv"))
steps_data_clean <- steps_data |> 
  clean_names() |>  #cleans the column names to have underscores 
  drop_na() |> 
  mutate(steps = as.numeric(gsub(",", "", steps)))  # removes commas 
  
  
```

###Problem 1b. Data Visulization
```{r}
steps_data_summary <- steps_data_clean |> 
group_by(school_day) |> #group data by site
  summarise( #calculating summary statistics
    n = n(),
    mean = mean(steps),
    sd = sd(steps),
    se = sd / sqrt(n),
    t_crit = qt(0.975, df = n - 2),
    ci_lower = mean - t_crit * se,
    ci_upper = mean + t_crit * se) |>
  select(school_day, mean, sd, se, ci_lower, ci_upper) |>  #only display certain statistics
  mutate(across(mean:ci_upper, ~ round(.x, 1))) #rounding those statistics

ggplot(steps_data_clean,
       aes(x = school_day, y = steps, color = school_day)) + #setting up x and y axis coloring points by site
  geom_jitter( #customizing jitter points
    position = position_jitter(width = 0.2, height = 0),
    shape = 21,
    fill = NA,
    alpha = 0.5,
    size = 2) +
  stat_summary( #adding point at group mean
    fun = mean,
    geom = "point",
    size = 3) +
  stat_summary( #adding standard error bars
    fun.data = mean_se,
    geom = "errorbar",
    width = 0.1) +
  scale_color_manual( #adding color
    values = c(
      yes = "red",
      no = "blue")) + 
  scale_y_continuous(
    breaks = seq(0, 35000, by = 5000),   # adjust max to match your data
    labels = scales::comma) +
  theme_classic() + #cleaning backgroud and removing legend
  theme(legend.position = "none") +
  labs( #labeling x, y, and titles
    title = "Steps vs School Day",
    subtitle = "Jason Han",
    x = "School Day",
    y = "Average Steps")

```

###Problem 1c. Caption
[Figure 1. Average daily step count is higher on non-school days than school days. The mean number of steps is greater on non-school days (n = 11) compared to school days (n = 25), with ±1 standard error whiskers and individual observations shown as semi-transparent open circles (red = school day, blue = non-school day). Step data were collected over multiple days as part of data collection for ENVS 193DS Homework 3.]

###Problem 1d. Data Table
```{r}
steps_data_summary |> #creating table using the summary data
  gt() |>
  cols_label( #renaming the columns
    school_day = "School Day",
    mean = "Mean",
    sd = "Standard Deviation",
    se = "Standard Error",
    ci_lower = "95% CI Lower",
    ci_upper = "95% CI Upper") |>
  fmt_number( #formating to one decimal
    columns = everything(),
    decimals = 1) |>
tab_header( #adding title
    title = "Steps vs School Day")

```

